### ISSUE TITLE
Will no longer be updated to the Raku ecosystem

### ISSUE THREAD

**Issue by lizmat** [hartenfels/Javascript-SpiderMonkey#5]
Hello,

Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org).  The language and its ecosystem are [moving forward](https://github.com/Raku/problem-solving/pull/318).

This means that these distributions:

- https://github.com/hartenfels/JavaScript-SpiderMonkey
- https://github.com/hartenfels/Text-Markdown-Discount

will no longer be checked for updates by the Raku ecosystem.

This means that you will need to move your module to the [zef ecosystem](https://deathbykeystroke.com/articles/20210120-faq-zef-ecosystem.html) on the next update you make to these distributions.  Otherwise your update will simply not be seen by the ecosystem.

If you are no longer interested in maintaining these distributions, you can have these distributions moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

This can be as easy as confirming that in a response to this issue.

Again, thank you for your time and efforts!

On behalf of the Raku Steering Council,

Elizabeth Mattijsen

**Comment by hartenfels** [comment]
Hi Elizabeth,

I'm no longer interested in maintaining these distributions, so they can be moved to the adoption center and picked up by someone else if they consider them useful. Let me know if there's anything I should be doing in that regard.

**Comment by lizmat** [comment]
Thanks for your reply!

As to Javascript::SpiderMonkey, it looks like it has never left the launch pad, so I suggest you archive that repo and I will remove that module from the p6c ecosystem.

On the other hand, I see that Text::Markdown::Discount has open Pull Requests.

In that case it would be best to move the repository to raku-community-modules.

If that is ok with you, then there are two ways of doing that:

- you give me maintain access to this repo, and I will then transfer it to raku-community-modules

- I give you maintain access to raku-community-modules, so you can do the transfer yourself.

If either is too involved for you, then I'll just fork the repos into raku-community-modules and will transport the PRs manually.

**Comment by hartenfels** [comment]
I've invited you to the Markdown repo, looks like you have to accept the invitation before I can give you a maintainer role in it. Also apparently I have to wait with archiving the JavaScript repo or else this issue here will become uncommentable, so I'll do that once the rest is done.

**Comment by lizmat** [comment]
I have accepted it just now

**Comment by hartenfels** [comment]
Yeah looks like I can't give you maintainer access, I can only add you as a "collaborator", whatever that is.

But I accepted the invitation to raku-community-modules and transferred the repo there myself, that seems to have worked? If so, feel free to close this issue.

**Comment by lizmat** [comment]
Yep, that worked.

Thanks, I'll take it from here  :-)
